### ISSUE TITLE
Using github actions, mirror the github repo.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [Prajwal-Koirala/fuchsia#1]

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Update the source code
    runs-on: ubuntu-latest
    steps:
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          cd fuchsia.git/
          git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Update the source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          cd fuchsia.git/
          git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code.
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Update the source code.
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory.
        uses: actions/checkout@v2
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          cd fuchsia.git/
          git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code.
on: [push, pull_request]
#on:
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  build:
    name: Update the source code.
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory.
        uses: actions/checkout@v2
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          cd fuchsia.git/
      - name: Push the latest changes to github
        run: git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code.
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Update the source code.
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory.
        uses: actions/checkout@v2
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
      - name: Push the latest changes to github
        run: |
          cd fuchsia.git/
          git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Updating Fushia Source Code.
on: [push, pull_request]
jobs:
  build:
    name: Update the source code.
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory.
        uses: actions/checkout@v2
      - name: Get the current url for the repository.
        run: ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
      - name: Update the git configs on your local machine.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download the most recent version of the fushia source code.
        run: |
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          cd fuchsia.git/
      - name: Push the latest changes to github
        run: git push --mirror ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone --bare https://fuchsia.googlesource.com/fuchsia
          ORIGIN_GIT_URL=$(git remote -v | head -n1 | awk '{print $2}')
          cd fuchsia.git/
          git push --mirror --force ${ORIGIN_GIT_URL}
```

**Comment by Prajwal-Koirala** [comment]
```
name: Automatically update fuchsia
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Automatically update fuchsia
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Update fuchsia automatically
        run: git clone --bare "https://fuchsia.googlesource.com/fuchsia" "${HOME}/fuchsia.git/"
      - name: Push the github workflow file to github.
        run: curl "https://raw.githubusercontent.com/Prajwal-Koirala/fuchsia/main/.github/workflows/auto-update.yml" --create-dirs -o "${HOME}/fuchsia.git/.github/workflow/auto-update.yml"
      - name: Push the changes to github.
        run: git -C "${HOME}/fuchsia.git/" push --mirror --force "$(git remote -v | head -n1 | awk '{print $2}')"
```
